# Generated by Django 4.1 on 2023-05-13 07:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailOrPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailorphone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mail Or Phone',
                'verbose_name_plural': 'Mail Or Phones',
            },
        ),
        migrations.CreateModel(
            name='MailPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'MailPass',
                'verbose_name_plural': 'Mail Passes',
            },
        ),
        migrations.CreateModel(
            name='PhoneNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
